// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: orders.proto

package orderspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year1         int32                  `protobuf:"varint,1,opt,name=year1,proto3" json:"year1,omitempty"`
	Month1        int32                  `protobuf:"varint,2,opt,name=month1,proto3" json:"month1,omitempty"`
	Year2         int32                  `protobuf:"varint,3,opt,name=year2,proto3" json:"year2,omitempty"`
	Month2        int32                  `protobuf:"varint,4,opt,name=month2,proto3" json:"month2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetYear1() int32 {
	if x != nil {
		return x.Year1
	}
	return 0
}

func (x *OrderRequest) GetMonth1() int32 {
	if x != nil {
		return x.Month1
	}
	return 0
}

func (x *OrderRequest) GetYear2() int32 {
	if x != nil {
		return x.Year2
	}
	return 0
}

func (x *OrderRequest) GetMonth2() int32 {
	if x != nil {
		return x.Month2
	}
	return 0
}

type OrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalBruto      float64                `protobuf:"fixed64,1,opt,name=total_bruto,json=totalBruto,proto3" json:"total_bruto,omitempty"`
	SaleFeeTotal    float64                `protobuf:"fixed64,2,opt,name=sale_fee_total,json=saleFeeTotal,proto3" json:"sale_fee_total,omitempty"`
	MedianTax       float64                `protobuf:"fixed64,3,opt,name=median_tax,json=medianTax,proto3" json:"median_tax,omitempty"`
	TotalLiquido    float64                `protobuf:"fixed64,4,opt,name=total_liquido,json=totalLiquido,proto3" json:"total_liquido,omitempty"`
	PeriodProcessed string                 `protobuf:"bytes,5,opt,name=period_processed,json=periodProcessed,proto3" json:"period_processed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetTotalBruto() float64 {
	if x != nil {
		return x.TotalBruto
	}
	return 0
}

func (x *OrderResponse) GetSaleFeeTotal() float64 {
	if x != nil {
		return x.SaleFeeTotal
	}
	return 0
}

func (x *OrderResponse) GetMedianTax() float64 {
	if x != nil {
		return x.MedianTax
	}
	return 0
}

func (x *OrderResponse) GetTotalLiquido() float64 {
	if x != nil {
		return x.TotalLiquido
	}
	return 0
}

func (x *OrderResponse) GetPeriodProcessed() string {
	if x != nil {
		return x.PeriodProcessed
	}
	return ""
}

var File_orders_proto protoreflect.FileDescriptor

const file_orders_proto_rawDesc = "" +
	"\n" +
	"\forders.proto\x12\x06orders\"j\n" +
	"\fOrderRequest\x12\x14\n" +
	"\x05year1\x18\x01 \x01(\x05R\x05year1\x12\x16\n" +
	"\x06month1\x18\x02 \x01(\x05R\x06month1\x12\x14\n" +
	"\x05year2\x18\x03 \x01(\x05R\x05year2\x12\x16\n" +
	"\x06month2\x18\x04 \x01(\x05R\x06month2\"\xc5\x01\n" +
	"\rOrderResponse\x12\x1f\n" +
	"\vtotal_bruto\x18\x01 \x01(\x01R\n" +
	"totalBruto\x12$\n" +
	"\x0esale_fee_total\x18\x02 \x01(\x01R\fsaleFeeTotal\x12\x1d\n" +
	"\n" +
	"median_tax\x18\x03 \x01(\x01R\tmedianTax\x12#\n" +
	"\rtotal_liquido\x18\x04 \x01(\x01R\ftotalLiquido\x12)\n" +
	"\x10period_processed\x18\x05 \x01(\tR\x0fperiodProcessed2M\n" +
	"\fOrderService\x12=\n" +
	"\x0eGetTotalOrders\x12\x14.orders.OrderRequest\x1a\x15.orders.OrderResponseB\fZ\n" +
	"./orderspbb\x06proto3"

var (
	file_orders_proto_rawDescOnce sync.Once
	file_orders_proto_rawDescData []byte
)

func file_orders_proto_rawDescGZIP() []byte {
	file_orders_proto_rawDescOnce.Do(func() {
		file_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)))
	})
	return file_orders_proto_rawDescData
}

var file_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orders_proto_goTypes = []any{
	(*OrderRequest)(nil),  // 0: orders.OrderRequest
	(*OrderResponse)(nil), // 1: orders.OrderResponse
}
var file_orders_proto_depIdxs = []int32{
	0, // 0: orders.OrderService.GetTotalOrders:input_type -> orders.OrderRequest
	1, // 1: orders.OrderService.GetTotalOrders:output_type -> orders.OrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_proto_init() }
func file_orders_proto_init() {
	if File_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_proto_goTypes,
		DependencyIndexes: file_orders_proto_depIdxs,
		MessageInfos:      file_orders_proto_msgTypes,
	}.Build()
	File_orders_proto = out.File
	file_orders_proto_goTypes = nil
	file_orders_proto_depIdxs = nil
}
